### ISSUE TITLE
`Independent`

### ISSUE THREAD

**Issue by micahstubbs** [distillpub/post--feature-visualization#10]
![screen shot 2017-11-07 at 1 46 13 pm](https://user-images.githubusercontent.com/2119400/32521663-3dc31a64-c3c9-11e7-936f-cc88f9ade53c.png)

https://www.google.com/search?q=independant

**Comment by ludwigschubert** [comment]
Fixed; thanks again!

**Comment by micahstubbs** [comment]
👍
