### ISSUE TITLE
Just some small typos

### ISSUE THREAD

**Issue by rdipietro** [distillpub/post--feature-visualization#14]
Visualizations of all channel are available in the appendix. (channels)

This article focusses on feature visualization. (focuses)

In the following sections we’ll examine techniques to get diverse visualizations, understand how neurons interact, and avoid high frequency artefacts. (artifacts)

How can we chose a preconditioner that will give us these beneﬁts? (choose)

used in adverserial work (adversarial)

As long as a correlation is consistent across spatial positions — such as the correlation between a pixel and its left neighbor being the same across all positions of an image — the Fourier coefﬁcients will be independant variables. (independent)

**Comment by Canas** [comment]
I'll add a few others I found :)

The objectives we’ve mentioned only scratch the surface of possibile objectives. (possible)

Additionally, the optimisation may make examples be different in an unnatural way. (optimization, for consistency)

Gradient blurring[15]  is equivalent to gradient descent in a different paramaterization of image space, (parameterization)

**Comment by ludwigschubert** [comment]
Yay for all your work and attention! Will fix on Monday. :-)
