### ISSUE TITLE
Gram matrix notation unclear - multiplication seems element-wise, but is actually a dot product

### ISSUE THREAD

**Issue by sliorde** [distillpub/post--feature-visualization#15]
In footnote 3, I think that the notation is confusing. For specific <d-math>i<d-math> and <d-math>j</d-math>, the element  <d-math>G_{i,j}</d-math> is a number, equal to the dot product between the (flattened) response of filter <d-math>i</d-math> and filter <d-math>j</d-math>. But the formula makes it seem as if we do an element-wise multiplication (without summation), between <d-math>\text{layer}_n\text{[:, :, i]}</d-math> and <d-math>\text{layer}_n\text{[:, :, j]} </d-math>. Such an element-wise multiplication would result in a matrix, and not in a scalar. I know that there is a "dot" in there, but I would also add a summation sign, or at least mention that the operator is a dot product which results in a scalar.

**Comment by ludwigschubert** [comment]
Sorry for the late response, I used your suggestion almost directly:

![image](https://user-images.githubusercontent.com/1167977/44543745-47501980-a6c5-11e8-8a5f-cd086a23749c.png)
