### ISSUE TITLE
Feature Visualization Article not correctly displayed

### ISSUE THREAD

**Issue by lfrdm** [distillpub/post--feature-visualization#18]
The newest article "Feature Visualization" [link](https://distill.pub/2017/feature-visualization/) is not correctly displayed. 
Unsure of the bug, but figures are displayed way too big and the overall alignment of divs seems to be off. I tryed IE 11.1770.14393.0 and Firefox 45.3.0. Other articles are displayed correctly with both browsers on first sight.

**Comment by colah** [comment]
Thanks for the bug report. Could you provide a screenshot?
