### ISSUE TITLE
Appendix "Layer" images not loading in Firefox

### ISSUE THREAD

**Issue by bryangingechen** [distillpub/post--feature-visualization#23]
When I visit e.g., [the appendix page for Layer 3a](https://distill.pub/2017/feature-visualization/appendix/googlenet/3a.html) using Firefox 60.0.1 on either my macOS or Windows systems, none of the images load.

(They do load if I use Chrome.)

**Comment by ludwigschubert** [comment]
While there's still an overflow styling bug, images load for me in modern versions of Firefox. Sorry to have left this lying until it got fixed!
