### ISSUE TITLE
Table #feature-vis-history wraps poorly on iPad

### ISSUE THREAD

**Issue by redblobgames** [distillpub/post--feature-visualization#25]
https://distill.pub/2017/feature-visualization/#feature-vis-history

Above browser width 1051px it displays correctly. 

From 1024px to 1050px it wraps the last column. From 1000px to 1023px it's using smaller text (css breakpoint) but it still wraps the last column. From 768px to 999px it wraps two columns. In this entire range from 768px to 1050px there's unused space in the margins — the table could be wider and not wrap.

<img width="880" alt="screen shot 2018-08-28 at 05 38 01" src="https://user-images.githubusercontent.com/8757369/44723347-9068ea80-aa84-11e8-86d7-25813087c5a2.png">

Under 768px there's no longer any space in the margins, so it necessarily wraps.

I don't know what to actually *do* about it though. Although the margin has plenty of space, it'd be inconsistent with the rest of the page CSS to use the margin in this way. Maybe shrink the font size further from 768px to 1050px? Or maybe shrink the spacers. The left column might also shrink to make it not wrap.

I only noticed this because I was reading on the iPad (10.5") and it wrapped both in landscape and portrait mode.

**Comment by ludwigschubert** [comment]
See #31 — f6e1c39 implements at least a fixed size + scroll :-) Thanks, Amit!
