### ISSUE TITLE
s/neuron to responds/neuron responds

### ISSUE THREAD

**Issue by micahstubbs** [distillpub/post--feature-visualization#27]
s/`neuron to responds`/`neuron responds`

![Screen Shot 2019-03-27 at 3 50 19 PM](https://user-images.githubusercontent.com/2119400/55117424-0e878100-50a8-11e9-8ef8-8912b607b2f5.png)

**Comment by ludwigschubert** [comment]
Fixed in #21 ! :-) Thanks, Micah!
