### ISSUE TITLE
expand on basis directions comment

### ISSUE THREAD

**Issue by micahstubbs** [distillpub/post--feature-visualization#28]
it seems that others have also found this passage harder than normal to parse. https://stackoverflow.com/questions/47268920/how-to-understand-individual-neurons-are-the-basis-directions-of-activation-spa

![Screen Shot 2019-03-27 at 3 54 19 PM](https://user-images.githubusercontent.com/2119400/55117602-a2f1e380-50a8-11e9-9f91-7c750571351a.png)

**Comment by ludwigschubert** [comment]
I attempted a rewrite of that section:
![image](https://user-images.githubusercontent.com/1167977/55362089-df00bc00-548d-11e9-8668-6bf4cbddfcf4.png)

We by now have a lot more to say on this topic, and it's tempting to reorganize and rewrite the entire section, but for now I hope this is an improvement for most readers.
