### ISSUE TITLE
match the text in joint optimization diagram default view

### ISSUE THREAD

**Issue by micahstubbs** [distillpub/post--feature-visualization#29]
It would be reduce cognitive load if the default selection for the joint optimization diagram matched the selection described in the text.  

The text says `black and white` + `mosaic`.   The diagram could show this `black and white` + `mosaic` view by default.

# suggested
![Screen Shot 2019-03-27 at 3 56 08 PM](https://user-images.githubusercontent.com/2119400/55117805-3fb48100-50a9-11e9-9fe8-2380ea8ba7f7.png)

# current
![Screen Shot 2019-03-27 at 3 55 45 PM](https://user-images.githubusercontent.com/2119400/55117814-43e09e80-50a9-11e9-9372-dbc35df05aa3.png)

**Comment by ludwigschubert** [comment]
Thanks Micah, that does make more sense. :-)
