### ISSUE TITLE
ux: freeze header and scroll rows in regularization options table

### ISSUE THREAD

**Issue by micahstubbs** [distillpub/post--feature-visualization#31]
ux: freeze header and scroll rows in regularization options table

this would make the post much more legible on phones and tablets.

![Screen Shot 2019-03-28 at 2 11 41 PM](https://user-images.githubusercontent.com/2119400/55193166-7222b480-5163-11e9-87f1-a1c9522bb73c.png)

**Comment by ludwigschubert** [comment]
I at least froze the entire table and made it scrollable in f6e1c39. Thanks for the proposal! :-)

**Comment by micahstubbs** [comment]
🎉
