### ISSUE TITLE
Availability of "Present Code Base"?

### ISSUE THREAD

**Issue by diego898** [distillpub/post--feature-visualization#9]
Just to clarify, under "Infrastructure Contributions" in "Author Contributions", the article mentions "Alex, Chris and Ludwig all contributed signiﬁcantly to reﬁning this into **the present code base**."

I know there is a [link to this code](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/deepdream/deepdream.ipynb) as having been previously published, but I am wondering if the "present code base" referes to the code used to generate all of the images and carry out the investigation of Googlenet. If so, is that code also available? 

**Thank for you another excellent article**

**Comment by colah** [comment]
As you noted, an early predecessor to our present code base is open source.

We'd love to open source our present infrastructure, but a small part of it is deeply entangled with some internal stuff. At some point, I hope to sit down and figure out how to separate things and get it open sourced, but it's always hard to find time. :/

So, hopefully it will be in the future!

**Comment by diego898** [comment]
Thanks Chris! I'll go ahead and close this as the question has been answered. Best of luck with everything.

**Comment by colah** [comment]
Of course. I'll try to remember to let you know if we get it open sourced. :)

**Comment by JiamingSuen** [comment]
@colah Thanks for this wonderful article! Hope you'll find some time to opensource the code. It would be really helpful to understand features in other network structures.
BTW, I wonder if it's possible to visualize features in structure like encoder-decoder used in semantic segmentation or depth/flow estimation? Have you ever tried on structures other than classification? Thanks!
